version: '1'
 
networks:
  net0:
    driver: bridge 
 
services:
  web-api:
    image: dev/work-balance:latest
    container_name: web-api
    depends_on:
      - "postgres"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080     
    networks:
      - net0  
  
  postgres:
    image: "postgres"
    container_name: "postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "WorkBalanceDb"
    ports:
      - 5432:5432
    restart: always
    networks:
      - net0